### ISSUE TITLE
Publish`et` as Date type

### ISSUE THREAD

**Issue by Xotabu4** [mpahuja/mocha-elk-reporter#5]
Hi, first of all thank you so much for this library. I used it for one pretty geeky idea, and it shows nice results so far. 

I noticed one problem, `et` field in posted results, thats timestamp right? it is reported as number, and i don't see way to reconfigure it for Date type. So i cannot create some date-based reports:
"No Compatible Fields: The "tests" index pattern does not contain any of the following field types: date"

![image](https://user-images.githubusercontent.com/3033972/47619811-5f8c4c80-daeb-11e8-81d9-ea3e6b1b01a3.png)

**Comment by mpahuja** [comment]
what version of ES are you using? if you can create an index with `et` as the date type and then use that index to send data, then it should work. I will look into ways to set that field as date type by default but currently that does not work out of the box. PRs welcome!

**Comment by ounis** [comment]
Hello, I had the same issue, and I just fixed it in this pull request https://github.com/mpahuja/mocha-elk-reporter/pull/13

I also added the option to set the username and password of elasticsearch in the env, because I run it on a CI server and I don't want to have the password in the code.

I would be really thankful if you can merge it quickly.
